name: dart_license_checker
description: Tool to view all dependencies (packages and plugins) you use and their licenses
version: 1.2.1
homepage: https://github.com/redsolver/dart_license_checker

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  path: ^1.8.2
  tint: ^2.0.0
  pana: ^0.21.14
  pubspec_parse: ^1.2.0
  barbecue: ^0.4.0

dev_dependencies:
  pedantic: ^1.11.1

executables:
  dart_license_checker: dart_license_checker
